// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pytorch_predict.proto

package torch_predict_protos

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArrayDataType int32

const (
	// Not a legal value for DataType. Used to indicate a DataType field
	// has not been set.
	ArrayDataType_DT_INVALID ArrayDataType = 0
	// Data types that all computation devices are expected to be
	// capable to support.
	ArrayDataType_DT_FLOAT      ArrayDataType = 1
	ArrayDataType_DT_DOUBLE     ArrayDataType = 2
	ArrayDataType_DT_INT32      ArrayDataType = 3
	ArrayDataType_DT_UINT8      ArrayDataType = 4
	ArrayDataType_DT_INT16      ArrayDataType = 5
	ArrayDataType_DT_INT8       ArrayDataType = 6
	ArrayDataType_DT_STRING     ArrayDataType = 7
	ArrayDataType_DT_COMPLEX64  ArrayDataType = 8
	ArrayDataType_DT_INT64      ArrayDataType = 9
	ArrayDataType_DT_BOOL       ArrayDataType = 10
	ArrayDataType_DT_QINT8      ArrayDataType = 11
	ArrayDataType_DT_QUINT8     ArrayDataType = 12
	ArrayDataType_DT_QINT32     ArrayDataType = 13
	ArrayDataType_DT_BFLOAT16   ArrayDataType = 14
	ArrayDataType_DT_QINT16     ArrayDataType = 15
	ArrayDataType_DT_QUINT16    ArrayDataType = 16
	ArrayDataType_DT_UINT16     ArrayDataType = 17
	ArrayDataType_DT_COMPLEX128 ArrayDataType = 18
	ArrayDataType_DT_HALF       ArrayDataType = 19
	ArrayDataType_DT_RESOURCE   ArrayDataType = 20
	ArrayDataType_DT_VARIANT    ArrayDataType = 21
)

var ArrayDataType_name = map[int32]string{
	0:  "DT_INVALID",
	1:  "DT_FLOAT",
	2:  "DT_DOUBLE",
	3:  "DT_INT32",
	4:  "DT_UINT8",
	5:  "DT_INT16",
	6:  "DT_INT8",
	7:  "DT_STRING",
	8:  "DT_COMPLEX64",
	9:  "DT_INT64",
	10: "DT_BOOL",
	11: "DT_QINT8",
	12: "DT_QUINT8",
	13: "DT_QINT32",
	14: "DT_BFLOAT16",
	15: "DT_QINT16",
	16: "DT_QUINT16",
	17: "DT_UINT16",
	18: "DT_COMPLEX128",
	19: "DT_HALF",
	20: "DT_RESOURCE",
	21: "DT_VARIANT",
}

var ArrayDataType_value = map[string]int32{
	"DT_INVALID":    0,
	"DT_FLOAT":      1,
	"DT_DOUBLE":     2,
	"DT_INT32":      3,
	"DT_UINT8":      4,
	"DT_INT16":      5,
	"DT_INT8":       6,
	"DT_STRING":     7,
	"DT_COMPLEX64":  8,
	"DT_INT64":      9,
	"DT_BOOL":       10,
	"DT_QINT8":      11,
	"DT_QUINT8":     12,
	"DT_QINT32":     13,
	"DT_BFLOAT16":   14,
	"DT_QINT16":     15,
	"DT_QUINT16":    16,
	"DT_UINT16":     17,
	"DT_COMPLEX128": 18,
	"DT_HALF":       19,
	"DT_RESOURCE":   20,
	"DT_VARIANT":    21,
}

func (x ArrayDataType) String() string {
	return proto.EnumName(ArrayDataType_name, int32(x))
}

func (ArrayDataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c476d63db6f757a, []int{0}
}

// Dimensions of an array
type ArrayShape struct {
	Dim                  []int64  `protobuf:"varint,1,rep,packed,name=dim,proto3" json:"dim,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayShape) Reset()         { *m = ArrayShape{} }
func (m *ArrayShape) String() string { return proto.CompactTextString(m) }
func (*ArrayShape) ProtoMessage()    {}
func (*ArrayShape) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c476d63db6f757a, []int{0}
}

func (m *ArrayShape) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayShape.Unmarshal(m, b)
}
func (m *ArrayShape) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayShape.Marshal(b, m, deterministic)
}
func (m *ArrayShape) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayShape.Merge(m, src)
}
func (m *ArrayShape) XXX_Size() int {
	return xxx_messageInfo_ArrayShape.Size(m)
}
func (m *ArrayShape) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayShape.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayShape proto.InternalMessageInfo

func (m *ArrayShape) GetDim() []int64 {
	if m != nil {
		return m.Dim
	}
	return nil
}

// Protocol buffer representing an array
type ArrayProto struct {
	// Data Type.
	Dtype ArrayDataType `protobuf:"varint,1,opt,name=dtype,proto3,enum=pytorch.eas.ArrayDataType" json:"dtype,omitempty"`
	// Shape of the array.
	ArrayShape *ArrayShape `protobuf:"bytes,2,opt,name=array_shape,json=arrayShape,proto3" json:"array_shape,omitempty"`
	// DT_FLOAT.
	FloatVal []float32 `protobuf:"fixed32,3,rep,packed,name=float_val,json=floatVal,proto3" json:"float_val,omitempty"`
	// DT_DOUBLE.
	DoubleVal []float64 `protobuf:"fixed64,4,rep,packed,name=double_val,json=doubleVal,proto3" json:"double_val,omitempty"`
	// DT_INT32, DT_INT16, DT_INT8, DT_UINT8.
	IntVal []int32 `protobuf:"varint,5,rep,packed,name=int_val,json=intVal,proto3" json:"int_val,omitempty"`
	// DT_STRING.
	StringVal [][]byte `protobuf:"bytes,6,rep,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	// DT_INT64.
	Int64Val             []int64  `protobuf:"varint,7,rep,packed,name=int64_val,json=int64Val,proto3" json:"int64_val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayProto) Reset()         { *m = ArrayProto{} }
func (m *ArrayProto) String() string { return proto.CompactTextString(m) }
func (*ArrayProto) ProtoMessage()    {}
func (*ArrayProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c476d63db6f757a, []int{1}
}

func (m *ArrayProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayProto.Unmarshal(m, b)
}
func (m *ArrayProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayProto.Marshal(b, m, deterministic)
}
func (m *ArrayProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayProto.Merge(m, src)
}
func (m *ArrayProto) XXX_Size() int {
	return xxx_messageInfo_ArrayProto.Size(m)
}
func (m *ArrayProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayProto.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayProto proto.InternalMessageInfo

func (m *ArrayProto) GetDtype() ArrayDataType {
	if m != nil {
		return m.Dtype
	}
	return ArrayDataType_DT_INVALID
}

func (m *ArrayProto) GetArrayShape() *ArrayShape {
	if m != nil {
		return m.ArrayShape
	}
	return nil
}

func (m *ArrayProto) GetFloatVal() []float32 {
	if m != nil {
		return m.FloatVal
	}
	return nil
}

func (m *ArrayProto) GetDoubleVal() []float64 {
	if m != nil {
		return m.DoubleVal
	}
	return nil
}

func (m *ArrayProto) GetIntVal() []int32 {
	if m != nil {
		return m.IntVal
	}
	return nil
}

func (m *ArrayProto) GetStringVal() [][]byte {
	if m != nil {
		return m.StringVal
	}
	return nil
}

func (m *ArrayProto) GetInt64Val() []int64 {
	if m != nil {
		return m.Int64Val
	}
	return nil
}

type PredictRequest struct {
	// Input tensors.
	Inputs []*ArrayProto `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Output filter.
	OutputFilter         []int32  `protobuf:"varint,2,rep,packed,name=output_filter,json=outputFilter,proto3" json:"output_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictRequest) Reset()         { *m = PredictRequest{} }
func (m *PredictRequest) String() string { return proto.CompactTextString(m) }
func (*PredictRequest) ProtoMessage()    {}
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c476d63db6f757a, []int{2}
}

func (m *PredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictRequest.Unmarshal(m, b)
}
func (m *PredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictRequest.Marshal(b, m, deterministic)
}
func (m *PredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictRequest.Merge(m, src)
}
func (m *PredictRequest) XXX_Size() int {
	return xxx_messageInfo_PredictRequest.Size(m)
}
func (m *PredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictRequest proto.InternalMessageInfo

func (m *PredictRequest) GetInputs() []*ArrayProto {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PredictRequest) GetOutputFilter() []int32 {
	if m != nil {
		return m.OutputFilter
	}
	return nil
}

// Response for PredictRequest on successful run.
type PredictResponse struct {
	// Output tensors.
	Outputs              []*ArrayProto `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PredictResponse) Reset()         { *m = PredictResponse{} }
func (m *PredictResponse) String() string { return proto.CompactTextString(m) }
func (*PredictResponse) ProtoMessage()    {}
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c476d63db6f757a, []int{3}
}

func (m *PredictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictResponse.Unmarshal(m, b)
}
func (m *PredictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictResponse.Marshal(b, m, deterministic)
}
func (m *PredictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictResponse.Merge(m, src)
}
func (m *PredictResponse) XXX_Size() int {
	return xxx_messageInfo_PredictResponse.Size(m)
}
func (m *PredictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictResponse proto.InternalMessageInfo

func (m *PredictResponse) GetOutputs() []*ArrayProto {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterEnum("pytorch.eas.ArrayDataType", ArrayDataType_name, ArrayDataType_value)
	proto.RegisterType((*ArrayShape)(nil), "pytorch.eas.ArrayShape")
	proto.RegisterType((*ArrayProto)(nil), "pytorch.eas.ArrayProto")
	proto.RegisterType((*PredictRequest)(nil), "pytorch.eas.PredictRequest")
	proto.RegisterType((*PredictResponse)(nil), "pytorch.eas.PredictResponse")
}

func init() { proto.RegisterFile("pytorch_predict.proto", fileDescriptor_5c476d63db6f757a) }

var fileDescriptor_5c476d63db6f757a = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcb, 0x6e, 0x9b, 0x4c,
	0x14, 0xfe, 0x81, 0xf8, 0xc2, 0xc1, 0x76, 0x26, 0xf3, 0x27, 0xaa, 0xd5, 0xaa, 0x0a, 0x75, 0x37,
	0xa8, 0x0b, 0xb7, 0x38, 0x16, 0xf2, 0x16, 0x07, 0xbb, 0x45, 0xa2, 0xc6, 0x19, 0x63, 0xab, 0x3b,
	0x34, 0x89, 0x71, 0x83, 0x44, 0x81, 0xc2, 0xb8, 0x92, 0x1f, 0xa5, 0xcf, 0xd6, 0x17, 0xe9, 0xb2,
	0x62, 0x98, 0xc4, 0xa9, 0x5a, 0xa9, 0xcb, 0xf3, 0xdd, 0xce, 0x37, 0x07, 0x01, 0x17, 0xf9, 0x81,
	0x65, 0xc5, 0xdd, 0x7d, 0x98, 0x17, 0xd1, 0x36, 0xbe, 0x63, 0xc3, 0xbc, 0xc8, 0x58, 0x86, 0x35,
	0x01, 0x0f, 0x23, 0x5a, 0x0e, 0x06, 0x00, 0x76, 0x51, 0xd0, 0xc3, 0xea, 0x9e, 0xe6, 0x11, 0x3e,
	0x07, 0x65, 0x1b, 0x7f, 0xe9, 0x4b, 0xba, 0x62, 0x28, 0x53, 0x19, 0x49, 0xa4, 0x1a, 0x07, 0xdf,
	0x65, 0x21, 0x5a, 0x72, 0xff, 0x3b, 0x68, 0x6c, 0xd9, 0x21, 0x8f, 0xfa, 0x92, 0x2e, 0x19, 0xbd,
	0xd1, 0xf3, 0xe1, 0x93, 0xbc, 0x21, 0xd7, 0x39, 0x94, 0xd1, 0xe0, 0x90, 0x47, 0xa4, 0x16, 0xe2,
	0x09, 0x68, 0xb4, 0xc2, 0xc3, 0xb2, 0xda, 0xd2, 0x97, 0x75, 0xc9, 0xd0, 0x46, 0xcf, 0xfe, 0xf4,
	0xf1, 0x12, 0x04, 0xe8, 0xb1, 0xd0, 0x25, 0xa8, 0xbb, 0x24, 0xa3, 0x2c, 0xfc, 0x46, 0x93, 0xbe,
	0xa2, 0x2b, 0x86, 0xcc, 0x6b, 0xb5, 0x39, 0xb8, 0xa1, 0x09, 0x7e, 0x05, 0xb0, 0xcd, 0xf6, 0xb7,
	0x49, 0xc4, 0x15, 0x27, 0xba, 0x62, 0x48, 0x5c, 0xa1, 0xd6, 0x68, 0x25, 0x79, 0x01, 0xad, 0x38,
	0xad, 0x13, 0x1a, 0xba, 0x62, 0x34, 0x38, 0xdf, 0x8c, 0x53, 0xee, 0x7f, 0x09, 0x50, 0xb2, 0x22,
	0x4e, 0x3f, 0x73, 0xbe, 0xa9, 0x2b, 0x46, 0x87, 0xa8, 0x35, 0x52, 0xd1, 0x97, 0xa0, 0xc6, 0x29,
	0xb3, 0xc6, 0x9c, 0x6d, 0x3d, 0x9e, 0xa5, 0xcd, 0xc1, 0x0d, 0x4d, 0x06, 0x3b, 0xe8, 0x2d, 0xeb,
	0xeb, 0x92, 0xe8, 0xeb, 0x3e, 0x2a, 0x19, 0x7e, 0x0b, 0xcd, 0x38, 0xcd, 0xf7, 0xac, 0xe4, 0x67,
	0xfc, 0xeb, 0x3b, 0xf9, 0x1d, 0x89, 0x90, 0xe1, 0xd7, 0xd0, 0xcd, 0xf6, 0x2c, 0xdf, 0xb3, 0x70,
	0x17, 0x27, 0x2c, 0x2a, 0xfa, 0x72, 0xd5, 0x92, 0x74, 0x6a, 0x70, 0xce, 0xb1, 0x81, 0x03, 0xa7,
	0x8f, 0x7b, 0xca, 0x3c, 0x4b, 0xcb, 0x08, 0x9b, 0xd0, 0xaa, 0x25, 0xff, 0xdc, 0xf4, 0xa0, 0x7b,
	0xf3, 0x43, 0x86, 0xee, 0x6f, 0x5f, 0x08, 0xf7, 0x00, 0x9c, 0x20, 0x74, 0x17, 0x1b, 0xdb, 0x73,
	0x1d, 0xf4, 0x1f, 0xee, 0x40, 0xdb, 0x09, 0xc2, 0xb9, 0xe7, 0xdb, 0x01, 0x92, 0x70, 0x17, 0x54,
	0x27, 0x08, 0x1d, 0x7f, 0x3d, 0xf5, 0x66, 0x48, 0x16, 0xa4, 0xbb, 0x08, 0xae, 0x46, 0x48, 0x11,
	0xd3, 0xda, 0x5d, 0x04, 0x13, 0x74, 0x72, 0xe4, 0x4c, 0x0b, 0x35, 0xb0, 0x06, 0xad, 0x7a, 0x9a,
	0xa0, 0xa6, 0x48, 0x59, 0x05, 0xc4, 0x5d, 0xbc, 0x47, 0x2d, 0x8c, 0xa0, 0xe3, 0x04, 0xe1, 0xb5,
	0xff, 0x71, 0xe9, 0xcd, 0x3e, 0x59, 0x63, 0xd4, 0x3e, 0x7a, 0xad, 0x31, 0x52, 0x85, 0x77, 0xea,
	0xfb, 0x1e, 0x02, 0x41, 0xdd, 0xf0, 0x24, 0x4d, 0x24, 0xdd, 0xd4, 0x3b, 0x3b, 0x0f, 0x63, 0x5d,
	0xa8, 0x8b, 0x4f, 0x41, 0xab, 0x8c, 0xbc, 0xbc, 0x69, 0xa1, 0xde, 0x13, 0xde, 0xb4, 0xd0, 0xa9,
	0x78, 0x2b, 0x77, 0x9b, 0x16, 0x42, 0x82, 0x16, 0xe3, 0x19, 0x3e, 0x83, 0xee, 0xb1, 0x97, 0x39,
	0x9a, 0x20, 0x2c, 0xaa, 0x7c, 0xb0, 0xbd, 0x39, 0xfa, 0x5f, 0xc4, 0x93, 0xd9, 0xca, 0x5f, 0x93,
	0xeb, 0x19, 0x3a, 0x17, 0x79, 0x1b, 0x9b, 0xb8, 0xf6, 0x22, 0x40, 0x17, 0x53, 0xe5, 0xa7, 0x24,
	0xdd, 0x36, 0xf9, 0x4f, 0x76, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x99, 0xcf, 0xbd, 0x26, 0x7d,
	0x03, 0x00, 0x00,
}
